<a href="https://colab.research.google.com/github/beafrnndz/Linear-Algebra_2ndSemester/blob/main/Activity_2_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Laboratory 4: Matrices

###Objectives
At the end of this activity you will be able to:
1. Be FAMILIAR WITH MATIRCES

##Discussion

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

###Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also hansy representauons of complex equations or multiple inter-related equations from 2 dimensional equations to even hundreds and thousands of them. 

Lets's say

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right.\\
C = \left\{
    \begin{array}\
        4w+x+2y-3z \\ 
        3w +2x -y +4z \\
        12w + (-2x) +2y- 7z
    \end{array}
\right. $$


$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 4 & 1 & 2 & -3 \\ 3 & 2 & -1 & 4 \\ 12 & -2 & 2 & -7\end{bmatrix} 
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [4]:
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [5]:
## Declaring a 2 x2 matrix
A = np.array([
    [1, 3,3],
    [3, 11,12]
])
describe_mat(A)
  


Matrix:
[[ 1  3  3]
 [ 3 11 12]]

Shape:	(2, 3)
Rank:	2



In [6]:
## Declaring a 3 x 2 matrix
B = np.array([
    [1, 3],
    [3, 11],
    [2,1]
])
describe_mat(B)
  


Matrix:
[[ 1  3]
 [ 3 11]
 [ 2  1]]

Shape:	(3, 2)
Rank:	2



In [7]:
## Declaring a Row Matrix
row_mat_1D = np.array ([
    1, 3, 2, 9
]) 
row_mat_2D = np.array ([
    [15, 3, 1, 2]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2 9]

Shape:	(4,)
Rank:	1

Matrix:
[[15  3  1  2]]

Shape:	(1, 4)
Rank:	2



In [8]:
col_mat = np.array ([
      [2],
      [12],
      [54]
])
describe_mat(col_mat)

Matrix:
[[ 2]
 [12]
 [54]]

Shape:	(3, 1)
Rank:	2



In [9]:
def describe_mat(matrix):
  is_square = True if matrix.shape [0] == matrix.shape [1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [10]:
square_mat = np.array([
    [7,5,2],
    [90,12,4],
    [7,5,1]
])

non_square_mat = np.array([
    [3,1,6],
    [39,42,7]

])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 7  5  2]
 [90 12  4]
 [ 7  5  1]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 3  1  6]
 [39 42  7]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## According to Elements

### Null Matrix

In [11]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape [0] == matrix.shape [1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')
    

In [12]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

In [13]:
zero_mat_row = np.zeros((7,8))
zero_mat_sqr = np.zeros((2,3))
zero_mat_rct = np.zeros((4,7))

print(f'Zero Row Matrix:\n{zero_mat_row}')
print(f'Zero Square Matrix:\n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix:\n{zero_mat_rct}')

Zero Row Matrix:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix:
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
ones_mat_row = np.ones((5,8))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((9,7))

print(f'Zero Row Matrix:\n{ones_mat_row}')
print(f'Zero Square Matrix:\n{ones_mat_sqr}')
print(f'Zero Rectangular Matrix:\n{ones_mat_rct}')

Zero Row Matrix:
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Zero Square Matrix:
[[1. 1.]
 [1. 1.]]
Zero Rectangular Matrix:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### Diagonal Matrix

In [15]:
np.array([
          [9,0,0],
          [0,10,0],
          [0,0,7]
])


array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  7]])

In [16]:
d = np.diag([8,4,1,6])
d.shape [0] == d.shape [1]
d

array([[8, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 6]])

###Identity Matrix

In [17]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

###Upper Triangular Matrix

In [18]:
np.array ([
           [5,6,7,8],
           [0,12,23,4],
           [0,0,12,5],
           [0,0,0,6,]
])

array([[ 5,  6,  7,  8],
       [ 0, 12, 23,  4],
       [ 0,  0, 12,  5],
       [ 0,  0,  0,  6]])

###Lower Triangular Matrix

In [19]:
np.array ([
           [0,0,0,8],
           [0,0,23,4],
           [0,3,12,5],
           [4,6,9,6,]
])

array([[ 0,  0,  0,  8],
       [ 0,  0, 23,  4],
       [ 0,  3, 12,  5],
       [ 4,  6,  9,  6]])

##Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$


In [20]:
A = np.array([5,3,-1])
print(A)

[ 5  3 -1]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [21]:
pa = np.array([
    [1, 1,1],
    [0,-4, -1],
    [0,0,10]
])
describe_mat(pa)
  

Matrix:
[[ 1  1  1]
 [ 0 -4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [22]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \left\{
    \begin{array}\
        1x+7y+8z \\ 
        2x +2y +2z \\
        4x + 6y +7z
    \end{array}
\right.\\
G= \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}\\
$$


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [23]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
G = \left\{
    \begin{array}\
        1x \\ 
        2x +2y  \\
        4x + 6y +7z
    \end{array}
\right.\\
G= \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}\\
$$


##Matrix Algebra

###Addition

In [24]:
A = np.array ([
               [1,2],
               [3,5],
               [3,4]
])
B = np.array ([
               [6,4],
               [5,2],
               [6,1]
])
A+B


array([[7, 6],
       [8, 7],
       [9, 5]])

In [25]:
54 + B *A

array([[60, 62],
       [69, 64],
       [72, 58]])

###Subtraction

In [45]:
A = np.array([
     [91,32], 
     [53,4],
     [61,9]       
])
B = np.array([
     [0,2], 
     [12,2],
     [11,2]
])
B - A

array([[-91, -30],
       [-41,  -2],
       [-50,  -7]])

###Element-wise Multiplication

In [46]:
A*B
np.multiply(A,B)

array([[  0,  64],
       [636,   8],
       [671,  18]])

In [47]:
7*A*B

array([[   0,  448],
       [4452,   56],
       [4697,  126]])

##Activities

#### Task 1

In [48]:
def mat_desc(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n\nSize:\t{matrix.size}\n')

In [51]:
A = np.array ([
    [1, 2,5,7],
    [3, 1,6,2],
    [5, 8,3,1] 
])
mat_desc(A)


Matrix:
[[1 2 5 7]
 [3 1 6 2]
 [5 8 3 1]]

Shape:	(3, 4)
Rank:	2

Size:	12



In [54]:
B = np.array ([
    [9, 5],
    [2, 9],
    [6, 7],
    [5, 8]
])
mat_desc(B)

Matrix:
[[9 5]
 [2 9]
 [6 7]
 [5 8]]

Shape:	(4, 2)
Rank:	2

Size:	8



In [55]:
C = np.array([
    [8, 2,4,6,3],
    [9, 4,3,5,6],
    [1, 5,3,9,7],
    [1, 9,8,1,5],
    [9, 4,3,5,6]
])
mat_desc(C)

Matrix:
[[8 2 4 6 3]
 [9 4 3 5 6]
 [1 5 3 9 7]
 [1 9 8 1 5]
 [9 4 3 5 6]]

Shape:	(5, 5)
Rank:	2

Size:	25



In [26]:
def describe_mat(matrix):
   if(matrix.shape[0] == matrix.shape[1]):
     square =True
     print('Square i2')
   else:
     print('dehins square')

In [27]:
sqr = np.array([
    [1,6,1,1],
    [3,33,282,24],
    [20,46,58,6]
])
describe_mat(sqr)

dehins square


In [28]:
sqr = np.array([
    [1,6,1,1],
    [3,33,282,24],    
    [6,6,2,1],
    [20,46,58,6]
])
describe_mat(sqr)

Square i2


In [29]:
sqr = np.array([
      [1,2,3],
      [8,32,6]
  
])
describe_mat(sqr)

dehins square


In [30]:
def describe_mat(matrix):
  zeros = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zeros == matrix).all()):
    print('ZERO SIYA')
  else:
    print('DI SIYA ZERO!')

In [31]:
zeros = np.array([
      [1,2,3],
      [1,2,3]
  
])
describe_mat(zeros)

DI SIYA ZERO!


In [32]:
zeros = np.array([
      [0,0,0],
      [0,0,0]
  
])
describe_mat(zeros)

ZERO SIYA


In [57]:
def mat_desc(matrix):
  if(matrix.size > 0):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print('Matrix is not empty')
  else:
    print('Matrix is empty')
    

In [58]:
empty_mat = np.array([])
mat_desc(empty_mat)

Matrix is empty


In [59]:
empty_mat = np.array([
    [1,2,5,1,5,9],
    [3,3,8,2,6,8],
    [2,4,8,6,8,3],
    [5,5,6,6,9,1],
    [9,7,4,6,2,9]

])
mat_desc(empty_mat)

Matrix is not empty


In [60]:
empty_mat = np.array([
    [2,2,5,1,4,3],
    [3,9,6,2,8,9]

])
mat_desc(empty_mat)

Matrix is not empty


In [39]:
def mat_desc(matrix):
  zeros = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zeros == matrix).all()):
    print('Matrix is zero')
  else:
    print('Matrix is not zero')

In [40]:
zeros = np.array([
      [0,0,4],
      [0,0,0]
  
])
mat_desc(zeros)

Matrix is not zero


###Task 2

In [61]:
def mat_operations(matrix1, matrix2):
  matrix1 = np.array(matrix1)
  matrix2 = np.array(matrix2)
  print('Matrix 1 entries are:\n',matrix1)
  print('Matrix 2 entries are:\n', matrix2)
  if(matrix1.shape != matrix2.shape):
    print('A non-square matrix cannot perform an operation')
    return
  print('Sum:')
  summ=matrix1 + matrix2
  print(summ)
  print('Difference:')
  diff= matrix1-matrix2
  print(diff)
  print('Element-wise multiplication:') 
  ewm = matrix1*matrix2
  print(ewm)
  print('Element-wise division:')
  ewd = matrix1/matrix2
  print(ewd)

In [43]:
mat_operations([
    [2,1,6,1,2,5], 
    [6,7,7,2,3,9],
    [3,3,9,6,7,4],
    [3,4,6,6,5,6]],

    [[1,2,2,3,9,3], 
    [1,2,2,1,1,4],
    [1,2,1,3,1,5],
    [3,6,9,6,7,6]])

Matrix 1 entries are:
 [[2 1 6 1 2 5]
 [6 7 7 2 3 9]
 [3 3 9 6 7 4]
 [3 4 6 6 5 6]]
Matrix 2 entries are:
 [[1 2 2 3 9 3]
 [1 2 2 1 1 4]
 [1 2 1 3 1 5]
 [3 6 9 6 7 6]]
Sum:
[[ 3  3  8  4 11  8]
 [ 7  9  9  3  4 13]
 [ 4  5 10  9  8  9]
 [ 6 10 15 12 12 12]]
Difference:
[[ 1 -1  4 -2 -7  2]
 [ 5  5  5  1  2  5]
 [ 2  1  8  3  6 -1]
 [ 0 -2 -3  0 -2  0]]
Element-wise multiplication:
[[ 2  2 12  3 18 15]
 [ 6 14 14  2  3 36]
 [ 3  6  9 18  7 20]
 [ 9 24 54 36 35 36]]
Element-wise division:
[[2.         0.5        3.         0.33333333 0.22222222 1.66666667]
 [6.         3.5        3.5        2.         3.         2.25      ]
 [3.         1.5        9.         2.         7.         0.8       ]
 [1.         0.66666667 0.66666667 1.         0.71428571 1.        ]]
