<a href="https://colab.research.google.com/github/beafrnndz/Linear-Algebra_2ndSemester/blob/main/Laboratory_6_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

##Laboratory 6: Matrix Operations

##Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
A = np.array ([
    [1,-2,5],
    [6,2,4]
])
A

array([[ 1, -2,  5],
       [ 6,  2,  4]])

In [4]:
AT1 = np.transpose(A)
AT1

array([[ 1,  6],
       [-2,  2],
       [ 5,  4]])

In [5]:
AT2 = A.T
AT2

array([[ 1,  6],
       [-2,  2],
       [ 5,  4]])

In [6]:
np.array_equiv(AT1,AT2)

True

In [7]:
B = np.array([
      [1,7,3],
      [4,2,6]
])
B.shape

(2, 3)

In [8]:
np.transpose(B).shape

(3, 2)

In [9]:
B.T.shape

(3, 2)

##Dot Product

In [10]:
X = np.array([
    [1,2],
    [8,3],
    [2,4]
])
Y = np.array([
    [-9,2,1],
    [0,4,2]
])

In [11]:
np.dot(X,Y)

array([[ -9,  10,   5],
       [-72,  28,  14],
       [-18,  20,  10]])

In [12]:
X.dot(Y)

array([[ -9,  10,   5],
       [-72,  28,  14],
       [-18,  20,  10]])

In [13]:
X @ Y

array([[ -9,  10,   5],
       [-72,  28,  14],
       [-18,  20,  10]])

In [14]:
np.matmul(X,Y)

array([[ -9,  10,   5],
       [-72,  28,  14],
       [-18,  20,  10]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}4&4\\7&0\\0&1\end{bmatrix}, B = \begin{bmatrix}10&3\\4&31\\0&4\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [15]:
A = np.array([
    [4, 4],
    [2, 8]
])
B = np.array([
    [13,2,5],
    [3,13,5],
    [-1,-2,5]
])
C = np.array([
    [0,7],
    [1,2],
    [3,6]
])
D = np.array([
    [3,2],
    [5,3],
    [8,9]

])
print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)

(2, 2)
(3, 3)
(3, 2)
(3, 2)


In [16]:
B @ C

array([[ 17, 125],
       [ 28,  77],
       [ 13,  19]])

In [17]:
D@A

array([[ 16,  28],
       [ 26,  44],
       [ 50, 104]])

In [18]:
A @ C.T

array([[28, 12, 36],
       [56, 18, 54]])

In [19]:
C @ D.T

array([[14, 21, 63],
       [ 7, 11, 26],
       [21, 33, 78]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [20]:
A = np.array([
    [1,6,2],
    [9,5,3],
    [1,4,2]
])
B = np.array([
    [0,9,4],
    [-4,5,-5],
    [-2,6,3]
])
C = np.array([
    [0,0,3],
    [1,4,7],
    [8,3,2]
])

In [60]:
Z = np.zeros(A.shape)
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
A@Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.array_equal(A@Z, Z)

True

In [24]:
A@B

array([[-28,  51, -20],
       [-26, 124,  20],
       [-20,  41, -10]])

In [25]:
B@A

array([[ 85,  61,  35],
       [ 36, -19,  -3],
       [ 55,  30,  20]])

In [26]:
np.array_equiv(A@B, B@A)

False

In [27]:
A@(B@C)

array([[-109,  144,  233],
       [ 284,  556,  830],
       [ -39,  134,  207]])

In [28]:
(A@B)@C

array([[-109,  144,  233],
       [ 284,  556,  830],
       [ -39,  134,  207]])

In [29]:
np.array_equiv(A@(B@C),(A@B)@C)

True

In [30]:
A@(B+C)

array([[ -6,  81,  29],
       [  3, 153,  88],
       [  0,  63,  25]])

In [31]:
A@B+A@C

array([[ -6,  81,  29],
       [  3, 153,  88],
       [  0,  63,  25]])

In [32]:
np.array_equiv(A@(B+C),A@B+A@C)

True

In [33]:
(B+C)@A

array([[ 88,  73,  41],
       [ 80,  35,  25],
       [ 92, 101,  49]])

In [34]:
B@A+C@A

array([[ 88,  73,  41],
       [ 80,  35,  25],
       [ 92, 101,  49]])

In [35]:
np.array_equiv((B+C)@A,B@A+C@A)

True

In [36]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
A@I

array([[1., 6., 2.],
       [9., 5., 3.],
       [1., 4., 2.]])

In [38]:
A

array([[1, 6, 2],
       [9, 5, 3],
       [1, 4, 2]])

In [39]:
np.array_equiv(A@I, A)

True

##Determinants

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laborat[link text](https://)ory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [40]:
G = np.array([
    [6,7],
    [3,0]
])
np.linalg.det(G)

-21.0

In [41]:
H = np.array([
              [3,8,1],
              [0,4,2],
              [7,3,7]
])
np.linalg.det(H)

149.99999999999997

In [42]:
I = np.array([
              [3,8,1,4],
              [0,4,2,7],
              [7,3,7,-9],
              [1,4,6,-3]
])
np.linalg.det(I)

-1545.000000000001

### Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [43]:
M = np.array([
    [4,3],
    [2, -9],
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [44]:
P = np.array([
              [5,8,3],
              [-5,-3,-5],
              [6,2,-7]
])
Q = np.linalg.inv(P)
Q

array([[-0.09090909, -0.18181818,  0.09090909],
       [ 0.19061584,  0.15542522, -0.02932551],
       [-0.02346041, -0.11143695, -0.07331378]])

In [45]:
Q@P

array([[ 1.00000000e+00,  8.32667268e-17,  1.80411242e-16],
       [ 9.02056208e-17,  1.00000000e+00, -1.28369537e-16],
       [ 2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

##TASK 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [49]:
S = np.array([
    [7,3,5,0],
    [0,2,4,8],
    [-4,6,-3,7],
    [11,7,3,5]
])
T= np.array([
    [4,-2,5,5],
    [2,4,1,3],
    [0,9,3,0],
    [8,9,6,8]
])
U = np.array([
    [2,2,1,4],
    [8,9,4,6],
    [0,9,0,2],
    [-7,-9,5,8]
])

In [56]:
X = np.zeros(S.shape)
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
S@X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.array_equal(S@X, X)

True

In [64]:
S@T

array([[ 34,  43,  53,  44],
       [ 68, 116,  62,  70],
       [ 52,  68,  19,  54],
       [ 98,  78, 101, 116]])

In [65]:
T@S

array([[ 63,  73,  12,  44],
       [ 43,  41,  32,  54],
       [-12,  36,  27,  93],
       [120, 134,  82, 154]])

In [66]:
np.array_equiv(S@T, T@S)

False

In [67]:
S@(T@U)

array([[ 104,  536,  426,  852],
       [ 574, 1108,  882, 1652],
       [ 270,  401,  594, 1086],
       [   8,  763,  990, 1990]])

In [68]:
(S@T)@U

array([[ 104,  536,  426,  852],
       [ 574, 1108,  882, 1652],
       [ 270,  401,  594, 1086],
       [   8,  763,  990, 1990]])

In [69]:
np.array_equiv(S@(T@U),(S@T)@U)

True

In [70]:
S@(T+U)

array([[ 72, 129,  72, 100],
       [ 28,  98, 110, 154],
       [ 43,  24,  74, 124],
       [141, 145, 165, 248]])

In [71]:
S@T+S@U

array([[ 72, 129,  72, 100],
       [ 28,  98, 110, 154],
       [ 43,  24,  74, 124],
       [141, 145, 165, 248]])

In [73]:
np.array_equiv(S@(T+U),S@T+S@U)

True

In [74]:
(T+U)@S

array([[117, 117,  39,  87],
       [149, 149, 114, 184],
       [ 10,  68,  69, 175],
       [139, 181,  20, 157]])

In [75]:
T@S+U@S

array([[117, 117,  39,  87],
       [149, 149, 114, 184],
       [ 10,  68,  69, 175],
       [139, 181,  20, 157]])

In [76]:
np.array_equiv((T+U)@S,T@S+U@S)

True

In [77]:
L = np.eye(4)
L

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
S@L

array([[ 7.,  3.,  5.,  0.],
       [ 0.,  2.,  4.,  8.],
       [-4.,  6., -3.,  7.],
       [11.,  7.,  3.,  5.]])

In [79]:
S

array([[ 7,  3,  5,  0],
       [ 0,  2,  4,  8],
       [-4,  6, -3,  7],
       [11,  7,  3,  5]])

In [80]:
np.array_equiv(S@L, S)

True